### ISSUE TITLE
[ubuntu 22] No active package detective.

### ISSUE THREAD

**Issue by octav8us** [Norbert515/detective#11]
upon writing
`flutter pub global run detective` 
 I get 

> No active package detective.

**Comment by Norbert515** [comment]
How did you install it? Installing and running needs to be done with the same command.

**Comment by octav8us** [comment]
just typed 
`flutter pub global activate -sgit https://github.com/Norbert515/detective.git
`

**Comment by Norbert515** [comment]
Can you activate it with Dart instead of Flutter? Alternatively, try re-installing it.

Here is a link explaining the activation of packages: https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path

**Comment by octav8us** [comment]
it worked  when i tried it with dart instead of flutter.
thanks
