### ISSUE TITLE
Could not find an option named "vmservice-out-file".

### ISSUE THREAD

**Issue by Hesamedin** [Norbert515/detective#13]
Hello Norbert,

I just noticed my build command doesn't work. This is the command I used to build my project:
```
flutter build apk --debug --dart-define flavor=development --target=lib/main_development.dart --vmservice-out-file=detective_connect.txt
```

This is the error I received:
```
Could not find an option named "no-enable-impeller".
```

I can confirm that `--vmservice-out-file` is missing when I run `flutter drive -h`.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
```

**Comment by Norbert515** [comment]
Hey, I'm not sure if this issue is related to Detective. Are getting the same error if you remove `--vmservice-out-file=detective_connect.txt`?

Additionally, I don't think Detective will work if you pre-build the APK as there is no connection between the target device and your PC (you'd have to manually fetch the service URL yourself).

**Comment by Hesamedin** [comment]
Thanks, Norbert for your reply. ah, yes, it is not the problem with Detective at all. Yes, I can build and run without `--vmservice-out-file` command.
It seems that `--vmservice-out-file` has been removed from the list of flutter commands. Do you know if there is any replacement?
