### ISSUE TITLE
Crash on macOS when using keyboard shortcuts

### ISSUE THREAD

**Issue by orestesgaolin** [Norbert515/detective#2]
1. Open detective
2. Try to make screenshot with CMD + shift + 4
3. Crash occurs

btw crash occurs when using other keyboard shortcuts e.g. Shift + any letter

v0.0.5-fix
macOS Big Sur

**Comment by Norbert515** [comment]
I've been able to reproduce this and #1. Only occurs on MacOS and in release mode, which is weird.

Will have to do some investigation.

**Comment by Norbert515** [comment]
Found the issue, will create a new built once it is fixed in Flutter

flutter/flutter#72393

**Comment by Norbert515** [comment]
Fixed with https://github.com/Norbert515/detective/commit/62626d60bf3e648efe6dc4525b0b264b2e72032e
