### ISSUE TITLE
Application Not Loading

### ISSUE THREAD

**Issue by ArneSaknussemm89** [Norbert515/detective#5]
Upon updating to v0.0.12, when running `detective` from the application root, nothing happens. The app doesn't load and there are no error messages thrown or anything.

Using macOS Big Sur - Version 11.1

```
⇒  flutter doctor                                                               
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
    ! Error: Justin Langley’s iPhone is not connected. Xcode will continue when Justin Langley’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
```

**Comment by Norbert515** [comment]
Fixed - reinstall the current version with 
```
flutter pub global activate -sgit https://github.com/Norbert515/detective.git
```

**Comment by ArneSaknussemm89** [comment]
Just did, now seeing this in the console:
```
⇒  detective
Can't load Kernel binary: Invalid SDK hash.
Connecting to ws://127.0.0.1:50362/ws
```

**Comment by Norbert515** [comment]
Hey, I checked and it seemed to work on my side. Try fully deleting detective and reinstalling it. It is located here:|
https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path

In the git folder

**Comment by ArneSaknussemm89** [comment]
So I deactivated the application, removed everything from `.pub-cache/bin` and `.pub-cache/git` related to detective and reinstalled. Now I'm seeing:
```
Can't load Kernel binary: Invalid SDK hash.
Could not find a file named "pubspec.yaml" in "/Users/justinlangley/.pub-cache/git/detective-b03f9ec081510c9cb83f0da2bdb79257afb1aefa".
```

I tried removing it again and running `flutter pub cache repair` and then reinstalled. Same issue above.
